remote_theme: sighingnow/jekyll-gitbook
title: '[game-title] idea'
toc: true
description: Bookmark this to keep an eye on my project updates!
plugins:
  - jekyll-relative-links
  - jekyll-toc
relative_links:
  enabled: true
  collections: true
include:
  - 'README.md'
