remote_theme: daattali/beautiful-jekyll@6.0.1
title: '[game-title] homepage'
description: Bookmark this to keep an eye on my project updates!
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - 'README.md'
