remote_theme: sighingnow/jekyll-gitbook
title: '_game-title_ idea'
toc:
  enabled: true
  h_min: 1
  h_max: 3
description: Bookmark this to keep an eye on my project updates!
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true
regenerate: true

markdown_ext: markdown,mkdown,mkdn,mkd,md

plugins:
  - jekyll-readme-index
